### ISSUE TITLE
Use Typescript instead of Javascript

### ISSUE THREAD

**Issue by Voroniyx** [iAsure/discord-arts#10]
Hey, I just wanted to ask why you don't write the package in Typescript? That's much easier for type checks and so on. I could start rewriting it

**Comment by iAsure** [comment]
Hi! that would be great, although right now I'm working on a big update which completely changes the code, maybe after that I can consider moving it to TS 🫡

**Comment by Voroniyx** [comment]
That's good. I would be happy to help with the switch to Typescript
