### ISSUE TITLE
Legit? Can everyone see it?

### ISSUE THREAD

**Issue by bsikora491** [iAsure/discord-arts#22]
Most of these not everyone can see it, unless you share it via a link or plugin… so does this actually make people see it without extra work?

**Comment by iAsure** [comment]
@bsikora491 What are you referring to?

**Comment by bsikora491** [comment]
Simple really, so you have this on your discord for a profile card. Yet can everyone on the server see it without clicking links or expanding your card?  Or is it only certain people who have the app, using a certain browser or device or clicking links.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iAsure** [comment]
You mean **discord-arts.asure.dev/card**?

If so, it can be viewed almost anywhere, since it acts like an image on the internet, something like send web.com/image.png

https://discord-arts.asure.dev/card/339919990947971105
![Me](https://discord-arts.asure.dev/card/339919990947971105)

**Comment by bsikora491** [comment]
No I mean you have profile cards for discord and it’s different on each server you go to . Can anyone view the customized profile card instead of the default one, without clicking on links or the card itself? Can it be on multiple devices such as iOS browsers? Computer web browser ? iOS apps? Android apps? Etc if not this isn’t a legit profile card creator and just a fake one

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iAsure** [comment]
Yes, the module only generates the image with the option to customize it

So you can see it everywhere

**Comment by bsikora491** [comment]
Sorry I’m a little confused by this as I never used this before, just been looking into it. And hoping to find a solution because boy do I hate the default ones we have now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bsikora491** [comment]
So if you download the card, how do you put it on discord?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bsikora491** [comment]
Sorry I’m a little confused by this as I never used this before, just been looking into it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
