### ISSUE TITLE
Boosting Badges are Not showing in v14 d.js

### ISSUE THREAD

**Issue by ARYANOP-Radio** [iAsure/discord-arts#5]
peoples who have booster badges are not showing in profile card.

**Comment by tristycreeper6** [comment]
it only shows when they are boosting the guild the command is used in

**Comment by iAsure** [comment]
@ARYANOP-Radio This is due to a problem with the API that the module uses, it seems that they made some changes and now the booster badge is not displayed.

Sorry for the late reply
