### ISSUE TITLE
FetchError: invalid json response body at https://japi.rest/discord/v1/user/<id>

### ISSUE THREAD

**Issue by SimplySnox** [iAsure/discord-arts#9]
I included this package in my discord bot a couple days ago after seeing it in a discord servers forums, and it was working fine at the time. However, I just got back home after being gone for three days and went to work on the bot -- where I got the following error when trying to use the command.

(Command Handler): `Failed to execute command: banner`
(Package Error):
```diff
FetchError: invalid json response body at https://japi.rest/discord/v1/user/630858684418752523 reason: Unexpected token < in JSON at position 0
```
Screenshot:
![image](https://github.com/iAsure/discord-arts/assets/103229161/af2c0ee6-e261-444e-b769-6b734e6848ec)
- Using Replit temporarily until I get my PC repaired.
---
Out of curiosity, I clicked on the link to see if there was a JSON response, but I'd assume the server is down as I received this page:

![image](https://github.com/iAsure/discord-arts/assets/103229161/7ac03dce-4277-40f2-8616-9e923da24801)
- Taken on my laptop.

**Comment by iAsure** [comment]
Sorry about that, the API is not owned by me, so I have no control over it

I will see what I can do to avoid these problems in the future
